class CfgExileCustomCode 
{
ExileServer_system_trading_network_purchaseItemRequest = "overrides\ExileServer_system_trading_network_purchaseItemRequest.sqf";
ExileServer_system_trading_network_sellItemRequest = "overrides\ExileServer_system_trading_network_sellItemRequest.sqf";
ExileServer_system_trading_network_purchaseVehicleRequest = "overrides\ExileServer_system_trading_network_purchaseVehicleRequest.sqf";
ExileServer_system_trading_network_purchaseVehicleSkinRequest = "overrides\ExileServer_system_trading_network_purchaseVehicleSkinRequest.sqf";
ExileServer_system_trading_network_wasteDumpRequest = "overrides\ExileServer_system_trading_network_wasteDumpRequest.sqf";
};
